<?xml version="1.0"?>
<package format="3">
  <name>i2c_device_ros</name>
  <version>0.0.0</version>
  <description>C++ library to read/write from/to I2C devices</description>
  
  <maintainer email="mateusmenezes95@gmail.com">Mateus Menezes</maintainer>
  <author email="mateusmenezes95@gmail.com">Mateus Menezes</author>
  
  <license>MIT</license>
  
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rclcpp</build_depend>
  <build_export_depend>rclcpp</build_export_depend>
  <exec_depend>rclcpp</exec_depend>
  <test_depend>ament_lint_auto</test_depend>
  <doc_depend>doxygen</doc_depend>
</package>
